kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-platform-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: platform
