kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-nginx-pvc
  annotations: 
    volume.beta.kubernetes.io/storage-class: ceph-rbd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
