apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      role: nginx-test
      tier: froand
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
        role: nginx-test
        tier: froand
    spec:
      containers:
      - name: nginx
        image: docker.cinyi.com/senyint/nginx:v.10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    role: nginx-test
    tier: froand
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
    role: nginx-test
    tier: froand
