apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
      role: tomcat-test
      tier: tomcat-froand
  replicas: 4
  template:
    metadata:
      labels:
        app: tomcat
        role: tomcat-test
        tier: tomcat-froand
    spec:
      containers:
      - name: tomcat
        image: docker.cinyi.com:443/xiaofengdi/tomcat8
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    app: tomcat
    role: tomcat-test
    tier: tomcat-froand
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tomcat
    role: tomcat-test
    tier: tomcat-froand
