apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-node1-node2-volume-pv1
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: node1-node2-1
  glusterfs:
    endpoints: "glusterfs-node1-node2-volume"
    path: "node1-node2-volume"
    readOnly: false
