kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-node1-node2-volume-pvc1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: node1-node2-1
