kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-node1-node2-volume-pvc2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
  storageClassName: node1-node2-2
