apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-proxy-kubesystem-443
  namespace: kube-system
spec:
  tls:
  - hosts:
    - dashboard.cinyi.com
    secretName: ingress-secret-kube-system
  rules:
  - host: dashboard.cinyi.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
