apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-platform-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: platform
  glusterfs:
    endpoints: "glusterfs-cluster-endpoints"
    path: "testgfs"
    readOnly: false
