apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-bi-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: bi
  glusterfs:
    endpoints: "glusterfs-cluster-endpoints"
    path: "gv0"
    readOnly: false
