apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-admin
  namespace: kube-system
type: "kubernetes.io/rbd"
data:
  key: QVFBbXpzRmF2eE5lT1JBQVFBU3dmU1pFM3FrR0xjN2pSUm5vK3c9PQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-user
type: "kubernetes.io/rbd"
data:
  key: QVFBbXpzRmF2eE5lT1JBQVFBU3dmU1pFM3FrR0xjN2pSUm5vK3c9PQ==
