apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-rbd-provisioner
provisioner: kubernetes.io/rbd
parameters:
    monitors: 192.168.200.11:6789,192.168.200.12:6789,192.168.200.13:6789
    adminId: admin
    adminSecretName: ceph-secret-admin
    adminSecretNamespace: "kube-system"
    pool: rbd
    userId: admin
    userSecretName: ceph-secret-user
    imageFormat: "1"
    imageFeatures: "layering"
